# fly.toml app configuration file generated for nodash-dev on 2025-07-22T21:57:43Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nodash-dev'
primary_region = 'iad'

[build]

[env]
  NODE_ENV = "production"
  STORE_EVENTS = "flatfile"
  STORE_USERS = "flatfile"
  STORE_RATELIMIT = "memory"
  EVENTS_PATH = "/app/data/events"
  USERS_PATH = "/app/data/users"
  RATE_LIMIT_WINDOW = "3600"
  RATE_LIMIT_MAX = "1000"
  API_KEY_HEADER = "x-api-key"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[http_service.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

[[http_service.checks]]
  interval = "10s"
  grace_period = "5s"
  method = "GET"
  path = "/v1/health"
  protocol = "http"
  timeout = "2s"
  tls_skip_verify = false

[mounts]
  source = "nodash_data"
  destination = "/app/data"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
